openapi: 3.1.0
info:
  title: User API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get a paginated list of users.
      description: Retrieves a paginated list of users with optional filtering.
      parameters:
        - name: page
          in: query
          description: The page number to retrieve
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1

        - name: size
          in: query
          description: The number of users per page
          required: false
          schema:
            type: integer
            default: 20
            minimum: 10
            maximum: 100
      responses:
        200:
          description: Successful response with paginated users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Alice
                    email:
                      type: string
                      example: alice@example.com
        400:
          description: In the case incorrect query params are provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad request due to invalid parameters
