openapi: 3.1.0
info:
  title: User Management API
  description: User Management API
  version: 1.0.0
paths:

components:
  schemas:
    PersonalInfo:
      type: object
      properties:
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        birthdate:
          type: string
          format: date
          example: 2001-09-11
        email:
          type: string
          example: john.doe@example.com
      required:
        - first_name
        - last_name
        - birthdate
        - email

    Address:
      type: object
      properties:
        address_street:
          type: string
        address_city:
          type: string
        address_country:
          type: string
        address_postal_code:
          type: integer
      required:
        - address_country
        - address_postal_code
        - address_city
        - address_street

    Preferences:
      type: object
      properties:
        need_newsletter:
          type: boolean
          default: false
          description: If the user would like to receive news letter or not
          example: true
        language:
          type: string
          description: The language of the news letter
          enum:
            - mg
            - fr
            - en
          example: fr

    CreateUserProfile:
      type: object
      properties:
        personal_info:
          $ref: '#/components/schemas/PersonalInfo'
        address:
          $ref: '#/components/schemas/Address'
        preferences:
          $ref: '#/components/schemas/Preferences'
      required:
        - personal_info
        - address
        - preferences

    UserProfile:
        allOf:
          - type: object
            properties:
              identifier:
                type: string
                example: user-0123
            required:
              - identifier

          - $ref: "#/components/schemas/CreateUserProfile"